// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shizuwjqaocvenkkuynf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoaXp1d2pxYW9jdmVua2t1eW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODAwNjcsImV4cCI6MjA2OTY1NjA2N30.Sow1chS9edy14ToZ3aTRTsoD3A2fYOvsUlgh9XIzZ-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});