// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgmfxynlgghkuikqqrka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nbWZ4eW5sZ2doa3Vpa3FxcmthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwODM0OTQsImV4cCI6MjA2OTY1OTQ5NH0.ucmMBZmNWSy4DnUyi1t7yZe3hbdYj7zQ6KxaAXGUI1Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});